
version: '3.8'

services:
  flask_app:
    build: .
#    image: currency-detection-ms-server
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    restart: always
